### PR TITLE
Rebase to 3.17, migrate to s6v3

### PR DESCRIPTION
**Pull request by thespad**
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

------------------------------

 - [x] I have read the [contributing](https://github.com/linuxserver/docker-minetest/blob/master/.github/CONTRIBUTING.md) guideline and understand that I have made the correct modifications

------------------------------

### CODE REVIEW

**Comment by drizuid** [comment]
@kingbbq would you be willing to test this out for us? None of the team uses this, but I know we worked together on a PR last year.

you would just use `lspipepr/minetest:amd64-5.6.1-pkg-865a468e-pr-48` as the image (assuming amd64) if you're willing

**Review by aptalca — APPROVED** [review]

**Comment by KingBBQ** [comment]
just tested it with the new image (lspipepr/minetest:amd64-5.6.1-pkg-865a468e-pr-48) and worked fine: 
- used a existing world
- used the port parameter to change the port...
all good!

**Comment by KingBBQ** [comment]
BTW, running 10+ minetest servers based on this docker image, for schools etc. - thanks a lot for the great work :)

**Comment by drizuid** [comment]
> BTW, running 10+ minetest servers based on this docker image, for schools etc. - thanks a lot for the great work :)

Thanks! We were a bit unsure how we were going to test this effectively, we appreciate you!!

**Pull request merged**
