### PR TITLE
Add missing ncurses-dev

### PR DESCRIPTION
**Pull request by IvanTurgenev**
Is default on offical builds.
Is extremely useful as an admin i dont want lo enter the game everytime i need to issue a command.

[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]
	

 

------------------------------

We welcome all PR’s though this doesn’t guarantee it will be accepted.

## Description:

added ncurses depedency
## Benefits of this PR and context:

because is the default and is useful for server admins

## How Has This Been Tested?

```
version: "2.1"
services:
  minetest:
    image: linuxserver/minetest
    container_name: minetest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Bogota
      - CLI_ARGS="--gameid minetest" #optional
    volumes:
      - ./:/config/.minetest
    ports:
      - 30000:30000/udp
    restart: "no"
    entrypoint: ["/usr/bin/minetestserver", "--config", "/config/.minetest/main-config/minetest.conf","--terminal"]
    stdin_open: true
    tty: true
```
`docker attach minetest`

debian 10

## Source / References:

https://github.com/minetest/minetest
compilling they use ncurses

### CODE REVIEW

**Comment by IvanTurgenev** [comment]
@sparklyballs

**Comment by IvanTurgenev** [comment]
@thelamer

**Comment by thelamer** [comment]
@IvanTurgenev can you explain what this actually does ? 
Also our images are multi arched you need to add things to the other dockerfiles also (aarch64 and armhf)

**Comment by IvanTurgenev** [comment]
> @IvanTurgenev can you explain what this actually does ?
> Also our images are multi arched you need to add things to the other dockerfiles also (aarch64 and armhf)

it allows to issue commands from the terminal no need to open the game, it is default on minetest builds also 
imagen
imagen
```
    entrypoint: ["/usr/bin/minetestserver", "--config", "/config/.minetest/main-config/minetest.conf","--terminal"]
    stdin_open: true
    tty: true
```
with this i just docker attach issue command no need to open the game

**Comment by thelamer** [comment]
Ok but why the dev package? Does it need special compile flags for the bin or is this strictly a lib needed ? 
https://pkgs.alpinelinux.org/package/v3.12/main/x86_64/ncurses

**Comment by IvanTurgenev** [comment]
https://github.com/minetest/minetest/blob/b298b0339c79db7f5b3873e73ff9ea0130f05a8a/cmake/Modules/FindNcursesw.cmake
yeah i think it needs devel

**Comment by IvanTurgenev** [comment]
> Ok but why the dev package? Does it need special compile flags for the bin or is this strictly a lib needed ?
> https://pkgs.alpinelinux.org/package/v3.12/main/x86_64/ncurses


https://github.com/minetest/minetest/blob/b298b0339c79db7f5b3873e73ff9ea0130f05a8a/cmake/Modules/FindNcursesw.cmake
yeah i think it needs devel, no extra flags

**Pull request merged**
