### PR TITLE
added postgresql and prometheus

### LINKED ISSUE #36: Add PostgreSQL support
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

Compile Minetest server with support for PostgreSQL

------------------------------

## Desired Behavior

Minetest server should work with `pgsql_connection = `... in `world.mt` as described here: https://wiki.minetest.net/Database_backends#PostgreSQL

## Current Behavior

Minetest server crashes continually:

    2021-10-29 11:00:54: ACTION[Main]: Server: Shutting down
    2021-10-29 11:00:55: ERROR[Main]: An unhandled exception occurred: Database backend postgresql not supported.
    2021-10-29 11:00:55: ERROR[Main]: In thread 7fd9c4731c00:
    2021-10-29 11:00:55: ERROR[Main]: /tmp/minetest/src/main.cpp:f3: int main(int, char**): A fatal error occurred: Database backend postgresql not supported.

## Alternatives Considered

- Switching to a different database backend. But this seems like a fundamental feature of Minetest, so I think it would be worth for the container to provide this, too.
- Creating our own dockerfile based on this one. See notes below.
- Compiling and running Minetest outside of docker. This was the original way we want to change from. We installed `libpq-dev` (header files for libpq5) and compiled minetest with `-DPostgreSQL_TYPE_INCLUDE_DIR=/usr/include/postgresql/` on Ubuntu. This exact package name exists on Alpine as well, I have not yet tried whether dropping these two into the Dockerfile already does the job.

### PR DESCRIPTION
**Pull request by SharkyRawr**
## Description:
Modified Dockerfile, added alpine packages required for these two features.

## Benefits of this PR and context:
Ability to use PostgreSQL for storage and Prometheus for performance statistics.

## How Has This Been Tested?
Running my own server with world saved in postgres without issues. Prometheus integration delivers performance statistics.

## Source / References:
n/a

closes https://github.com/linuxserver/docker-minetest/issues/36

### CODE REVIEW

**Comment by PeterNerlich** [comment]
I'm probably just being stupid, but the build fails for me at `fetch additional game` with `tar: invalid tar magic`. It does the same on master though, so in the event I'm not just missing something it's probably not related to this PR. I just ran the instructions from README to build local (but making sure to actually use your repo and branch)

~~**EDIT:** Nevermind, I ran well out of disk space~~ Having that sorted out, the error still seems to persist. Where are the variables like `${MINETEST_RELEASE}` supposed to come from?

**Comment by aptalca** [comment]
Normally, our jenkins builder injects it as a docker build arg. When it's not injected, it is retrieved within the dockerfile: https://github.com/linuxserver/docker-minetest/blob/master/Dockerfile#L71-L74

However, they broke our ci and dockerfile when they did an upstream release for android only, without the amd64 binary: https://github.com/minetest/minetest/releases

We thought there would be another regular release that would fix everything, but there hasn't been one since. So our ci is currently disabled for this image.

**Comment by PeterNerlich** [comment]
Thank you, that helped me. Found out how to specify that variable myself and am happy to report that the build completed this time! I'll be testing whether it actually runs as intended by this PR when I have more time.

**Comment by aptalca** [comment]
@SharkyRawr @PeterNerlich 
We have a fix for the ci builds and a rebase to alpine 3.15 #39 . Can either of you quickly test this image before we merge it? After that this PR can be rebased on master branch and the build should succeed.

You can use this test image: `lspipepr/minetest:5.4.1-pkg-98b21676-pr-39`
Just replace `lscr.io/linuxserver/minetest` with the above

Thanks

**Comment by VagabondAzulien** [comment]
I'm interested in a build with Prometheus compiled. What needs to happen for this PR to be merged?

**Comment by drizuid** [comment]
> I'm interested in a build with Prometheus compiled. What needs to happen for this PR to be merged?

someone needs to test, as requested directly above your comment.

**Pull request closed without merging**
