### PR TITLE
use cpu cores

### PR DESCRIPTION
**Pull request by sparklyballs**
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

### CODE REVIEW

**Review by tobbenb — CHANGES_REQUESTED** [review]
Change - to dot on line 86 of the Readme 😉

**Comment by sparklyballs** [comment]
@tobbenb done

**Review by tobbenb — APPROVED** [review]

**Comment by tobbenb** [comment]
@sparklyballs Finally I found something to correct 😂

**Comment by sparklyballs** [comment]
you'll have to wait a long time for another

lol

**Pull request merged**
